import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  productList: any[] = []
  constructor() { }

  getAllProducts() {
    this.productList = [
      {
        name:'',
        category:'',
        modelNo:'',
        price:200,
        productImage:'../../assets/products/sincBasin.jpeg',
        description:'',
        allImages:[
          {
            id:1,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:2,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:3,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:4,
            image:'../../assets/products/sincBasin.jpeg'
          }
        ]
      },
      {
        name:'',
        category:'',
        modelNo:'',
        price:300,
        productImage:'../../assets/products/sincBasin.jpeg',
        description:'',
        allImages:[
          {
            id:1,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:2,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:3,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:4,
            image:'../../assets/products/sincBasin.jpeg'
          }
        ]
      },
      {
        name:'',
        category:'',
        modelNo:'',
        price:400,
        productImage:'../../assets/products/sincBasin.jpeg',
        description:'',
        allImages:[
          {
            id:1,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:2,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:3,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:4,
            image:'../../assets/products/sincBasin.jpeg'
          }
        ]
      },
      {
        name:'',
        category:'',
        modelNo:'',
        price:500,
        productImage:'../../assets/products/sincBasin.jpeg',
        description:'',
        allImages:[
          {
            id:1,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:2,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:3,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:4,
            image:'../../assets/products/sincBasin.jpeg'
          }
        ]
      },
      {
        name:'',
        category:'',
        modelNo:'',
        price:200,
        productImage:'../../assets/products/sincBasin.jpeg',
        description:'',
        allImages:[
          {
            id:1,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:2,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:3,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:4,
            image:'../../assets/products/sincBasin.jpeg'
          }
        ]
      },
      {
        name:'',
        category:'',
        modelNo:'',
        price:200,
        productImage:'../../assets/products/sincBasin.jpeg',
        description:'',
        allImages:[
          {
            id:1,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:2,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:3,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:4,
            image:'../../assets/products/sincBasin.jpeg'
          }
        ]
      },
      {
        name:'',
        category:'',
        modelNo:'',
        price:200,
        productImage:'../../assets/products/sincBasin.jpeg',
        description:'',
        allImages:[
          {
            id:1,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:2,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:3,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:4,
            image:'../../assets/products/sincBasin.jpeg'
          }
        ]
      },
      {
        name:'',
        category:'',
        modelNo:'',
        price:200,
        productImage:'../../assets/products/sincBasin.jpeg',
        description:'',
        allImages:[
          {
            id:1,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:2,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:3,
            image:'../../assets/products/sincBasin.jpeg'
          },
          {
            id:4,
            image:'../../assets/products/sincBasin.jpeg'
          }
        ]
      }
    ];
    return this.productList;
  }
}
